### ISSUE TITLE
自适应高度

### ISSUE THREAD

**Issue by milobluebell** [margox/braft-editor#110]
自适应高度，height属性设置为0之后，使用
`   min-height: 120px; 
    max-height: 300px;
    _height: 120px;
 `
还是不能自适应，能讲一下如何设置吗？ 其实我建议设置为一个option更好。

**Comment by margox** [comment]
你试试:
```css
body .BraftEditor-content{
  height: auto;
  min-height: 120px;
  max-height: 300px;
  overflow: auto;
}
```
