### ISSUE TITLE
无法识别空格的问题大家都是怎么解决的

### ISSUE THREAD

**Issue by smartcong007** [margox/braft-editor#185]
空格无效，要存的时候手动替换？

**Comment by margox** [comment]
有一个解决方案，在前台展示页面加如下的CSS规则:
```css
.content p{
  white-space: pre-wrap;
}
```
`.content p`这个选择器根据你的实际情况来写
