### ISSUE TITLE
使用forceNewLine [true]时选中内容居右会导致所有数据都居右

### ISSUE THREAD

**Issue by evolu6** [margox/braft-editor#189]
使用forceNewLine [true]时  选中部分内容居右  会导致所有数据都居右

**Comment by margox** [comment]
编辑器的文本居左居右其实是操作的光标所在行的区块的样式，forceNewLine设置true之后，换行的话不会生成新的区块，编辑器内所有的文字都属于同一个区块，所以会有这样的问题。
在新版本中将会移除forceNewLine属性，对于在展示页连续换行无法产生间隔的问题，只需要给p标签设置一个最低高度就行了，例如
```css
.article p{
  min-height: 1em;
}
```
