### ISSUE TITLE
多个图片float-left问题

### ISSUE THREAD

**Issue by jsososo** [margox/braft-editor#241]
关于多个图片同时使用float-left的问题，在编辑器内会出现这种分行的情况（这个用css处理到还是方便），麻烦的是后面那个，输出的html里的图片前面的p标签没有特殊的类名区分，所以如果设置了p标签的最小高度后会对显示造成影响
![i1](https://user-images.githubusercontent.com/25875263/46387606-0999d400-c6fa-11e8-85ba-15e4121d1e43.jpg)
![i2](https://user-images.githubusercontent.com/25875263/46387615-13233c00-c6fa-11e8-9fe8-518cf39aa01d.jpg)

**Comment by margox** [comment]
就是说给P设置最低高度，导致图片前面产生了不期望的空白是吧，这个我先想一下有啥子解决办法

**Comment by huangdou0204** [comment]
同样遇到了，图片同时导入多张后之间有间隔的行，如果是一张长途切割开的就会造成不能合并到一起的视觉效果，总会有一行空白

**Comment by margox** [comment]
@huangdou0204 你的这个问题比较好解决，用如下的css就行了：
```css
.image-wrap img{
  display: block; /*用于消除图片默认的下边距，或者用line-height:0;也行*/
}
.image-wrap + p:empty{
  display: none;
}
```
这样可以让连续的图片之间的p标签不显示

**Comment by margox** [comment]
@huangdou0204 你的这个问题比较好解决，用如下的css就行了：
```css
.image-wrap img{
  display: block; /*用于消除图片默认的下边距，或者用line-height:0;也行*/
}
.image-wrap + p:empty{
  display: none;
}
```
这样可以让连续的图片之间的p标签不显示

**Comment by margox** [comment]
@huangdou0204 这一段css是用在展示页的，用于清除html在实际展示的时候图片之间的间距，例如你的文章展示的div的class是article-content，那么在你展示页的css样式中加入下面这段就行:
```css
.article-content .image-wrap img{
  display: block; /*用于消除图片默认的下边距，或者用line-height:0;也行*/
}
.article-content .image-wrap + p:empty{
  display: none;
}
```
在编辑器中暂时没办法做到这样，因为必须要保留中间的空行以保持可编辑行，毕竟这个不是海报制作工具，没办法做到太专业的效果。

**Comment by huangdou0204** [comment]
> @huangdou0204 这一段css是用在展示页的，用于清除html在实际展示的时候图片之间的间距，例如你的文章展示的div的class是article-content，那么在你展示页的css样式中加入下面这段就行:
> 
> ```css
> .article-content .image-wrap img{
>   display: block; /*用于消除图片默认的下边距，或者用line-height:0;也行*/
> }
> .article-content .image-wrap + p:empty{
>   display: none;
> }
> ```
> 
> 在编辑器中暂时没办法做到这样，因为必须要保留中间的空行以保持可编辑性，毕竟这个不是海报制作工具，没办法做到太专业的效果。

我的展示端是RN写的，并不是Web展示形式，也是有中间转换层，而且单独做这种处理比较费事，如果要保持编辑行的话，可否在最后保留即可，中间部分去掉不行吗？或者通过类似开关的一个东西开处理是否需要空行，或者获取html 内容时做处理？

**Comment by margox** [comment]
@huangdou0204 得益于当前版本的扩展功能，可以用以下办法实现你的需求：

#### 定义一个block输出转换函数
```js
const blockExportFn = (contentState, block) => {

  const previousBlock = contentState.getBlockBefore(block.key)

  if (block.type === 'unstyled' && previousBlock && previousBlock.getType() === 'atomic') {
    return {
      start: '',
      end: '',
    }
  }

}
```

#### 在编辑器中使用这个函数
```jsx
<BraftEditor converts={{ blockExportFn }}/>
```

**Comment by margox** [comment]
@jsososo 如果你的html是用于在网页中显示，那么上面的CSS做法和blockExportFn做法应该都可以解决你的问题哦

**Comment by margox** [comment]
关于编辑器converts属性的文档还在整理中，涉及到的东西会比较复杂，我也很头疼怎么给其他基础不太好的用户解释明白

**Comment by jsososo** [comment]
嗯。试了一下确实可以了，之前自己在展示端给 .img-wrap 加了 margin-top所以在两行图片下面的文字会有异常。只用margin-bottom就ok了。

**Comment by jsososo** [comment]
嗯。试了一下展示端的样式没有问题了，之前对.img-wrap添加了margin-top所以两行图片猴下面的文字会有异常，只用margin-bottom就没问题了。然后对这种图片的工具条被遮挡的问题不是很清楚该如何去处理，肥肠感谢解答了
![image](https://user-images.githubusercontent.com/25875263/46926312-d133b780-d062-11e8-84c8-3e3d027e90ae.png)

**Comment by margox** [comment]
你这是左侧编辑右侧预览么？ 可以通过imageControls属性去掉一些不需要用到的图片工具

**Comment by jsososo** [comment]
其实他是被右边的图片挡住了，当时我不知道为什么调整position和z-index没有用

**Comment by margox** [comment]
因为编辑器内部的图片容器的z-index都是相同的值，按照规则，相同z-index的元素，排在后面的实际层级会比排在前面的高，你试试通过下面的css来hack一下，让被鼠标hover到的图片容器z-index加大一级：
```css
.bf-media:hover{
  z-index: 2;
}
```
