### ISSUE TITLE
如果插入图片会多一个空行，删除空行会把图片也删掉

### ISSUE THREAD

**Issue by git-lt** [margox/braft-editor#256]
这个bug，请解决一下，比如商品详情，是需要图片连续的，不能有空行，如果用直接替换掉，像文字段落这种，是需要空行的，希望可以手动正常删除空行！！！！

**Comment by margox** [comment]
这个问题并不是编辑器的bug，而是现有条件限制还没找到更好的办法，但是在展示页，你可以用下面的办法去掉连续图片之间的空格:

#### 用CSS隐藏
```css
.article-content .image-wrap img{
  display: block; /*用于消除图片默认的下边距，或者用line-height:0;也行*/
}
.article-content .image-wrap + p:empty{
  display: none;
}
```

#### 输出的时候不输出图片之后紧跟着的空行
```js
const blockExportFn = (contentState, block) => {

  const previousBlock = contentState.getBlockBefore(block.key)

  if (block.type === 'unstyled' && previousBlock && previousBlock.getType() === 'atomic') {
    return {
      start: '',
      end: '',
    }
  }

}

<BraftEditor converts={{ blockExportFn }}/>
```

#241
