### ISSUE TITLE
如何保留html片段中的空格

### ISSUE THREAD

**Issue by w4212598** [margox/braft-editor#290]
如题

**Comment by margox** [comment]
暂时的办法是在展示页面中设置如下的CSS:
```css
.article-content p{
  white-space: prewrap;
}
```
