### ISSUE TITLE
插入一个表格之后 用dangerouslySetInnerHTML显示的样式不对

### ISSUE THREAD

**Issue by mengmengdadetonghuayeah** [margox/braft-editor#304]

**Comment by margox** [comment]
额。。。显示啥样了？ 每个单元格都独立成了一行么?

**Comment by mengmengdadetonghuayeah** [comment]
对对 是的 有什么解决办法吗？

**Comment by margox** [comment]
升级一下braft-extensions@beta，实际版本号应该是0.0.12,修复了这个问题

**Comment by mengmengdadetonghuayeah** [comment]
请问一下 安装之后不独立成行了 但是显示的表格没有样式和边框

**Comment by margox** [comment]
恩，边框什么的需要你自己稍微设置一下，例如这样：
```css
.article-content table{
  border-style: hidden;
  border-collapse: collapse;
  border-spacing: 0;
}
.article-content table td{
  border: 1px solid #c5c5c5;
}
```
如果由编辑器直接在输出的时候加上边框样式，颜色宽度什么的不一定符合你们的UI规范，所以你们自己来设置样式更合适。
