### ISSUE TITLE
有序列表在编辑器中样式重叠

### ISSUE THREAD

**Issue by MinJieLiu** [margox/braft-editor#327]
![image](https://user-images.githubusercontent.com/6167727/50329182-fe07bd80-0530-11e9-8b01-aed917704e3c.png)
看了一下，在index.css 中编辑器的实现方式是通过 :before 选择器加了 `counter-increment` 。但是网页默认的样式是 `list-style: decimal;` 从而导致双重前缀的问题。

**Comment by margox** [comment]
应该是你有别处的样式影响到了，编辑器的里面的li本来已经是将list-style设置为none了的:
```css
.public-DraftStyleDefault-orderedListItem{
  list-style-type: none;
}
```
