### ISSUE TITLE
文字换行按enter不会换行 无效

### ISSUE THREAD

**Issue by guanguanqingchao** [margox/braft-editor#373]
按enter不会换行  按shift+enter可以换行，发现按enter时候 添加p标签，但是p标签没有高度，shift+enter的时候添加br
可否在按enter的时候也加br呢？
期待您的回复 谢谢!

**Comment by tangshengfei** [comment]
我也发现这个问题，不过我现在在前端显示的时候直接把空P标签替换成br标签了已达到换行效果。就等大佬修复了。。。

**Comment by margox** [comment]
@guanguanqingchao @tangshengfei 
在draftjs里面，直接按enter会生成一个一个自然段落（<p>），按shift+enter生成的则是一个软换行(<br>)。
一般情况下，直接用软换行也没啥问题，但是如果需要设置段落的文本对齐方式的话，就会遇到问题。因为文本对齐方式是针对一整个自然段的，如果编辑器中所有的换行都是用的br的话，那所有的段落实际上都是在一个p标签之内的，这时候如果设置文本左右对齐什么的，会发现整个内容都会被影响到。
在1.x版本中还有个forceNewLine属性可以强制让enter也生成软换行，在新版中已经去掉了。
对于生成的空的p标签在展示页面没有高度的问题，直接通过以下CSS解决即可:
```css
.content p{
  min-height: 1em;
}
/* 或者 */
.content p:empty{
  height: 1em;
}
```
