### ISSUE TITLE
段落缩进，且设置段落居左或居中后，样式有问题

### ISSUE THREAD

**Issue by coldice945** [margox/braft-editor#387]
不仅段落开头会缩进，整个段落也会跟着缩进。
个人建议 css 修改为：
```css
.bftd-1 {
  text-indent: 2em;
  display: initial
}

.bf-container .bftd-2 {
  text-indent: 4em;
  display: initial
}

.bf-container .bftd-3 {
  text-indent: 6em;
  display: initial
}

.bf-container .bftd-4 {
  text-indent: 8em;
  display: initial
}

.bf-container .bftd-5 {
  text-indent: 10em;
  display: initial
}

.bf-container .bftd-6 {
  text-indent: 12em;
  display: initial
}
```
