### ISSUE TITLE
回车输入<br />标签，并转行

### ISSUE THREAD

**Issue by z2x** [margox/braft-editor#502]
编辑器默认是回车插入p标签进行换行，要软回车才可以输入br标签，请教一下如何设置才能默认回车插入br标签转行呢？

**Comment by margox** [comment]
现在没有这种设置了，全部都用br的话，会有问题的，例如文本对齐方式之类的都会不能正常使用，因为全部内容本质上都是一个段落了，如果是因为p标签在展示的时候空行显示无效的问题，那解决方法有很多，例如通过CSS设置最低高度:
```css
.article-content p{
  min-height: 1em;
}
```
