### ISSUE TITLE
可以设置默认行高吗？

### ISSUE THREAD

**Issue by tykdn** [margox/braft-editor#515]

**Comment by margox** [comment]
```css
.my-editor p{
  line-height: 20px;
}
```
```JSX
<BraftEditor contentClassName="my-editor" />
```
试试
