### ISSUE TITLE
初始化字体颜色是灰色，有没有属性可以修改这个默认设置啊？

### ISSUE THREAD

**Issue by wo-de-ping-er** [margox/braft-editor#538]

**Comment by margox** [comment]
你这是被别的css污染样式了吧,审查元素看一下就知道了，可以自己用css再设置一下：
```css
.bf-content {
  color: #000;
}
```
