### ISSUE TITLE
复制粘贴内容p标签变成了span标签

### ISSUE THREAD

**Issue by clll7** [margox/braft-editor#553]
如题

**Comment by margox** [comment]
是在审查元素查看编辑器区域的时候看到的是span，还是通过`editorState.toHTML()`拿到的全是span？

**Comment by clll7** [comment]
在审查元素查看编辑器区域的时候看到的是span

**Comment by margox** [comment]
你不用关心这地方是啥样的，这个地方是draftjs按照另外的规则去渲染的，最终的内容你是要通过editorState.toHTML()才能获取到的，另外你可以看一下[使用前请了解](https://github.com/margox/braft-editor#%E4%BD%BF%E7%94%A8%E5%89%8D%E8%AF%B7%E4%BA%86%E8%A7%A3)

**Comment by clll7** [comment]
谢谢。问题是多行文本，复制进编辑器后变成了单行文本

**Comment by margox** [comment]
贴一下你的代码看看

**Comment by clll7** [comment]
[这篇文章](https://mp.weixin.qq.com/s?src=11&timestamp=1562122093&ver=1705&signature=DdJoL9RMELHGdVSCOoSqVsqKCjsjTVSpiBBA4bDGLkCGa7flqwKI7m9xFUAad1J-WUO3Gl-4wng9EO1sqB4vLrE5gVApCet8b3BlRyqwMDXGRRXjqhsn825uv4I-2jim&new=1)，复制内容进官网的demo就是那样。

![2](https://user-images.githubusercontent.com/6949822/60562823-b7223c80-9d8b-11e9-94a8-df7f1c20eee4.jpg)

![1](https://user-images.githubusercontent.com/6949822/60562813-b2f61f00-9d8b-11e9-9b71-60580154fbf6.jpg)

**Comment by margox** [comment]
好像是之前有个pr增加的CSS有点问题，你先用下面的外部css覆盖一下：
```css
body .bf-container .bftd-1,
body .bf-container .bftd-2,
body .bf-container .bftd-3,
body .bf-container .bftd-4,
body .bf-container .bftd-5,
body .bf-container .bftd-6{
  display: block;
}
```
