### ISSUE TITLE
添加隐藏工具栏功能和设为只读功能

### ISSUE THREAD

**Issue by avdbg** [margox/braft-editor#82]
因为生成的html和编辑时显示的有一些差别，所以我想要将编辑器的的标题栏隐藏并设置为只读来显示文章内容，但是发现没有设置的方式。
原本也想尝试直接使用draft的Editor组件进行显示，但发现无法显示添加的图片，源码中render相关的部分也比较复杂，所以希望添加这两个功能，谢谢！

**Comment by margox** [comment]
试试设置disabled属性，然后controls属性传一个空数组
```
<BraftEditor
  disabled={true}
  controls={[]}
>
```

**Comment by avdbg** [comment]
确实可以隐藏工具栏，但是这样文字颜色会变浅。

**Comment by margox** [comment]
@avdbg 一切css样式皆可hack

**Comment by margox** [comment]
添加下面的样式到你的全局样式中就行了。
```CSS
body .BraftEditor-container.disabled{
  opacity: 1;
  filter:none;
}
```
